# Generated by Django 4.2 on 2024-10-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstWEB", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
    ]
