# Generated by Django 4.2 on 2024-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstWEB", "0002_remove_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
